utils::globalVariables(c("KOSMOStestdata",
                         "KOSMOS2024KielQuartzSideExperimentStyletable",
                         "KOSMOS2024KielStyletable",
                         "KOSMOS2023HelgolandStyletable",
                         "KOSMOS2022BergenStyletable",
                         "KOSMOScurrentStyletable",
                         "KOSMOScurrentStatscols",
                         "KOSMOSdesignfeatures",
                         "KOSMOScurrentCategoricalVar",
                         "KOSMOScolumntable"
                         #"copepic"
))
